== Eclipse RCP example repository image:https://img.shields.io/badge/License-EPL%202.0-blue.svg["EPL 2.0", link="https://www.eclipse.org/legal/epl-2.0/"]

This is the example code for the https://learn.vogella.com/courses/details/rich-client-platform[Eclipse RCP commercial training] from vogella GmbH.
It is also used in the http://www.vogella.com/books/eclipsercp.html[Eclipse Rich Client Platform book].
=== Default branch

_main_ is the default branch of this repository. 
It contains the latest stable version of the code.

=== Running the application

Clone the project and import all projects except the projects with nattable into the Eclipse IDE.

Then open the _target-platform.target_ file of the _target-platform_ project and 
set this target definition as target platform for your workspace.

When the compile errors are gone the target platform has been properly set and the product located
 in the com.vogella.task.product project can be run.


=== Building the application

Use the following command one the command line to build the application using Tycho.

./mvnw clean verify


